DIRS += build/$(ARCH)/
DIRS += build/core/
DIRS += build/libc/
DIRS += build/device/
DIRS += bin/
DIRS += build/iso/boot/grub/

include src/x86_64/Makefile
include src/core/Makefile
include src/device/Makefile
include src/libc/Makefile
